apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp-service
spec:
  selector:
    app: fleetman-webapp
    type: front-end
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
