apiVersion: v1
kind: Pod
metadata:
  name: fleetman-webapp-pod
  labels:
    app: fleetman-webapp
spec:
  containers:
    - name: fleetman-webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

