apiVersion: v1
kind: ReplicationController
metadata:
  name: myFirstApp-RC
  labels:
    app: myFirstApp
    type: backend-service
spec:
  template:
    metadata:
      name: myFirstApp-Pod
      labels:
        app: myFirstApp
        type: backend-service
    spec:
      containers:
        - name: nginx
          image: nginx
  replicas: 3