apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue-service
spec:
  selector:
    app: fleetman-queue
  type: nodePort
  ports:
    - nodePort: 30010
      port: 8161
      targetPort: 8161
